---
- hosts: localhost
  collections:
     - community.general
  tasks:

   - name: "Send success notification message via Slack"
     community.general.slack:
       token: "{{ SLACK_TOKEN }}"
       channel: "{{ SLACK_CHANNEL }}"
       blocks:
         - type: section
           text:
             type: mrkdwn
             text: |-
               *Apache Server Deployment:*
               Your request was fullfiled successfully. Below you will find all the necessary information about your Apache Server and how to access it. Thank you for using our services!
         - type: context
           elements:
           - type: mrkdwn
             text: |
               *Hostname:* {{ MY_HOST }}
       msg: "Status: Success"
       color: '#338cc7'
     delegate_to: localhost
...
